config/routes.rb
Rails.application.routes.draw do
    
    resources :controllers
    resources :camps
    resources :camp_instructors
    resources :curriculums
    resources :instructors
    resources :locations
    resources :users
    resources :credit_cards
    resources :curriculums
    resources :families
    resources :students
    resources :registrations
    
    root to: 'home_page#index'
    
    resources :about_us
    resources :contact_us
    resources :privacy_page
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/student.rb
class Student < ApplicationRecord
    
    has_many :registrations
    has_many :camps, through: :registrations
    belongs_to :family
    
    #validations
    
    validates_presence_of :first_name, :last_name
    validates_presence_of :family_id
    validates_numericality_of :rating, :inclusion => 0..3000, :allow_nil => true
    
    
    validate :age
    validate :name
    validate :proper_name
    validate :set_rating
    validates_date :date_of_birth, :before => lambda {Date.today}, :before_message => "can't be in the future", allow_blank: true, on: :create
    ratings = [0] + (100..3000).to_a
    validates :rating, numericality: {only_integer: true, allow_blank: true}, inclusion: {in: ratings, allow_blank: true}
    validates_numericality_of :family_id
    
    
    #scopes
    
    scope :alphabetical, -> { order('last_name, first_name') }
    scope :active, -> { where(active: true) }
    scope :inactive, -> { where(active: false) }
    
    scope :at_or_above_rating, -> (floor) { where('rating >= ?', floor) }
    scope :below_rating, -> (ceiling) { where('rating < ?', ceiling) }
    
    
    before_update :remove_registration_when_inactive
    before_save :set_rating
    
    before_destroy do
        check_if_registered_for_past_camp
        if errors.present?
            #@destroyable = false
        else
            remove_registrations
        end
    end
    
    #methods
    
    def name
        "#{self.last_name}, #{self.first_name}"
    end
  
  def proper_name
    "#{self.first_name} #{self.last_name}"
  end
  
    def age
      return nil if date_of_birth.blank?
      (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
    end
    
    private
    
    def set_rating
       @rating = self.rating
       if @rating == nil
           @rating = 0
       end
    end
    
    private
    
    
    def registered_for_past_camp?
        !self.registrations.select{|i| i.camp.start_date < Date.current}.empty?
    end 
    
    def check_if_registered_for_past_camp 
        registered_for_past_camp?
    end 
    
    def remove_registrations
       upcoming = self.registrations.select{|i| i.camp.start_date >= Date.current }
       upcoming.each{|j| j.destroy}
    end
    
    
    def remove_registration_when_inactive 
        remove_registrations if !self.active
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
     params.require(:student).permit(:family_id, :first_name, :last_name, :date_of_birth, :rating, :active)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :family_id %>
    <%= form.select :family_id, options_from_collection_for_select(Family.all, 'id', 'family_name') %>
  </div>
  
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: 'first__name' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: 'last_name' %>
  </div>
  
  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth, id: 'date_of_birth' %>
  </div>
  
  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating, id: 'rating' %>
  </div>

  <div class="checkbox">
    <label><%= form.check_box :active %> Is this student active?</label>
  </div>
    


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<br><br><br>

<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<body>


<br><br><br>

<p id="notice"><%= notice %></p>

<% if @students.empty? %>
  <h3>There are no students in the system at this time</h3>
<% else %>

  <h2>Students</h2>

  <table>
    <thead>
      <tr>
        
        <th>First Name</th>
        <th>Last Name</th>
        <th>Family ID</th>
        <th>Date of Birth</th>
        <th>Rating</th>
        <th colspan = "5"></th>
        
      </tr>
    </thead>
    
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td> <%= link_to student.first_name, student %></td>
        <td> <%= link_to student.last_name, student %></td>
        <td> <%= link_to student.family_id, student %></td>
        <td> <%= link_to student.date_of_birth, student %></td>
        <td> <%= link_to student.rating, student %></td>
        
        
        <td> <%= link_to 'Edit', edit_student_path(student) %></td>
        
      </tr>
      <% end %>
    </tbody>
  </table>


  <% end %>

<br>
<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<br><br><br>

<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<br><br><br>

<p id="notice"><%= notice %></p>

<h3> Student Details</h3>

<p>
  <strong>First Name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Family ID:</strong>
  <%= @student.family_id %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @student.date_of_birth %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @student.rating %>
</p>

<p>
  <strong>Active:</strong>
  <%= @student.active ? "Yes" : "No" %>
</p>