config/routes.rb
Rails.application.routes.draw do
    
    resources :controllers
    resources :camps
    resources :camp_instructors
    resources :curriculums
    resources :instructors
    resources :locations
    resources :users
    resources :credit_cards
    resources :curriculums
    resources :families
    resources :students
    resources :registrations
    
    root to: 'home_page#index'
    
    resources :about_us
    resources :contact_us
    resources :privacy_page
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/camp.rb
class Camp < ApplicationRecord
  # relationships
  
  belongs_to :curriculum
  belongs_to :location
  has_many :camp_instructors
  has_many :instructors, through: :camp_instructors
  has_many :registrations
  has_many :students, through: :registrations

  # validations
  validates_presence_of :location_id, :curriculum_id, :time_slot, :start_date
  validates_numericality_of :cost, greater_than_or_equal_to: 0
  validates_date :start_date, :on_or_after => lambda { Date.today }, :on_or_after_message => "cannot be in the past", on:  :create
  validates_date :end_date, :on_or_after => :start_date
  validates_inclusion_of :time_slot, in: %w[am pm], message: "is not an accepted time slot"
  validates_numericality_of :max_students, only_integer: true, greater_than: 0, allow_blank: true
  validate :curriculum_is_active_in_the_system
  validate :location_is_active_in_the_system
  validate :camp_is_not_a_duplicate, on: :create
  validate :max_students_not_greater_than_capacity
  validate :check_for_camp_deactivation
  

  # scopes
  scope :alphabetical, -> { joins(:curriculum).order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :chronological, -> { order('start_date','end_date') }
  scope :morning, -> { where('time_slot = ?','am') }
  scope :afternoon, -> { where('time_slot = ?','pm') }
  scope :upcoming, -> { where('start_date >= ?', Date.today) }
  scope :past, -> { where('end_date < ?', Date.today) }
  scope :for_curriculum, ->(curriculum_id) { where("curriculum_id = ?", curriculum_id) }
  
  scope :full, -> {joins(:registrations).group(:camp_id).having('count(*) = max_students')}
  scope :empty, -> {joins(:registrations).group(:camp_id).having('count(*) = 0')}
  
    # instance methods
    
  def is_full?
    self.max_students <= enrollment
  end
  
  def enrollment
    self.registrations.count
  end
  
  def name
    self.curriculum.name
  end

  def already_exists?
    Camp.where(time_slot: self.time_slot, start_date: self.start_date, location_id: self.location_id).size == 1
  end

  # callbacks
  before_update :remove_instructors_from_inactive_camp
  before_update :check_for_camp_deactivation
  
  
  before_destroy do
    check_for_students_registered
    camp_instructors.delete_all
  end
  
  

  private
  
  def curriculum_is_active_in_the_system
    return if self.curriculum.nil?
    errors.add(:curriculum, "is not currently active") unless self.curriculum.active
  end

  def location_is_active_in_the_system
    return if self.location.nil?
    errors.add(:location, "is not currently active") unless self.location.active
  end

  def camp_is_not_a_duplicate
    return true if self.time_slot.nil? || self.start_date.nil? || self.location_id.nil?
    if self.already_exists?
      errors.add(:time_slot, "already exists for start date, time slot and location")
    end
  end

  def max_students_not_greater_than_capacity
    return true if self.max_students.nil? || self.location_id.nil?
    if self.max_students > self.location.max_capacity
      errors.add(:max_students, "is greater than the location capacity")
    end
  end
  
  
  #PHASE 4

  def remove_instructors_from_inactive_camp
    if !self.active
      self.camp_instructors.each{|ci| ci.destroy}
    end
  end
  
  def registration_for_camp_check?
    !self.registrations.length.zero?
  end
  
  def check_for_camp_deactivation
    return true if self.active
    registration_for_camp_check?

  end
  
  def check_for_students_registered
    registration_for_camp_check?

  end
    
    
  
 
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy]

  def index
    @camps = Camp.all
    @active_camps = Camp.all.active.alphabetical.paginate(:page => params[:active_camps]).per_page(10)
    @inactive_camps = Camp.all.inactive.alphabetical.paginate(:page => params[:inactive_camps]).per_page(1)
  end

  def show
    @instructors = @camp.instructors.alphabetical
  end

  def edit
  end

  def new
    @camp = Camp.new
  end

  def create
    @camp = Camp.new(camp_params)
    if @camp.save
      redirect_to camp_path(@camp), notice: "#{@camp.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    @camp.update(camp_params)
    if @camp.save
      redirect_to camp_path(@camp), notice: "#{@camp.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @camp.destroy
    redirect_to camps_url, notice: "#{@camp.name} was removed from the system."
  end

  private
    def set_camp
      @camp = Camp.find(params[:id])
    end

    def camp_params
      params.require(:camp).permit(:curriculum_id, :location_id, :cost, :start_date, :end_date, :time_slot, :max_students, :active)
    end
end

app/views/camps/_camp_details.html.erb
<div class="card blue lighten-2">
    <div class="card-content white-text">
        Camp Details
        <span class="card-title"><%=@camp.curriculum.name</span>
        
        <p><%= @camp.curriculum.description %></p>
        
        <h5> Information </h5>
        <p><strong>Location: </strong><%= @camp.location.name %></p>
        <p><strong>Dates: </strong><%= @camp.start_date.strftime("%m/%d/%y") %> - <%= @camp.end_date.strftime("%m/%d/%y") %></p>
        <p><strong>Camp: </strong>$<%= @camp.cost %>0</p>
        <p><strong>Slots Remaining: </strong><%# @camp.max_students - @camp.registrations.count %></p>
  </div>
        
    </div>
    
</div>

app/views/camps/_camp_instructor.html.erb
<div class="card indigo lighten-2">
  <div class="card-content white-text">
    <span class="card-title">Camp Instructors</span>
	  <% if @instructors.empty? %>
		<p>No instructors at this time</p>
	  <% else %>
      <ul>
        <% @instructors.each do |i| %>
          <li>
            <%= link_to(camp_instructor_path(id: camp_instructor_id_for(@camp, i)), method: :delete, class: 'remove') do %>
              x&nbsp;&nbsp;
            <% end %>
            <%= link_to i.proper_name, instructor_path(i) %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div class="card-action">
    <%= link_to "Add a new instructor", new_camp_instructor_path(camp_id: @camp.id) %>
    </div>
  </div>
</div>

app/views/camps/_form.html.erb
<%= form_with(model: camp, local: true) do |form| %>
  <% if camp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(camp.errors.count, "error") %> prohibited this camp from being saved:</h2>

      <ul>
      <% camp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :location_id %>
    <%= form.select :location_id, options_from_collection_for_select(Location.all, 'id', 'name'), {}, id: 'location_id' %>
  </div>


  <div class="field">
    <%= form.label :curriculum_id %>
    <%= form.select :curriculum_id, options_from_collection_for_select(Curriculum.all, 'id', 'name'), { include_blank: true }, id: 'curriculum_id' %>
  </div>
  
  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost, id: 'camp_cost' %>
  </div>
  
  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select(:start_date, prompt: true, id: 'camp_start_date') %>
  </div>
  
  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select(:end_date, prompt: true, id: 'camp_end_date') %>
  </div>
  
  <div class="field">
    <%= form.label :time_slot %>
    <%= form.select :time_slot, options_for_select([["Morning", "am"], ["Afternoon", "pm"]], form.object.time_slot), {}, id: 'camp_time_slot' %>
  </div>
  
  <div class="field">
    <%= form.label :max_students %>
    <%= form.text_field :max_students, id: 'camp_max_students' %>
  </div>

  <div class="checkbox">
    <label><%= form.check_box :active %> Is this camp active?</label>
  </div>
    


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/camps/edit.html.erb
<br><br><br>

<h1>Editing Camp</h1>

<%= render 'form', camp: @camp %>

<%= link_to 'Show', @camp %> |
<%= link_to 'Back', camps_path %>

app/views/camps/index.html.erb
<br><br><br>

<p id="notice"><%= notice %></p>

<% if @camps.empty? %>
  <h4>There are no camps in the system at this time</h4>
<% else %>

  <h2>Camps</h2>
  
  <table>
    <thead>
      <tr>
  
        <th>Name</th>
        <th>Start</th>
        <th>End</th>
        <th>Time</th>
        <th>Max Students</th>
        
      </tr>
    </thead>
    
    <tbody>
      <% @camps.each do |camp| %>
      <tr>
        
        <td> <%= link_to camp.curriculum.name, camp %></td>
        <td> <%= link_to camp.start_date.strftime("%m/%d/%y"), camp %></td>
        <td> <%= link_to camp.end_date.strftime("%m/%d/%y"), camp %></td>
        <td> <%= link_to camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
        <td> <%= link_to camp.max_students, camp %></td>
        
        <td> <%= link_to 'Edit', edit_camp_path(camp) %></td>
        
      </tr>
      <% end %>
    </tbody>
    

  </table>


  <% end %>

<br>
<%= link_to 'New camp', new_camp_path %>

app/views/camps/new.html.erb
<br><br><br>

<h1>New Camp</h1>

<%= render 'form', camp: @camp %>

<%= link_to 'Back', camps_path %>

app/views/camps/show.html.erb
<br><br><br>

<div class="card indigo lighten-2">
  <div class="card-content white-text">
    <span class="card-title"><%=@camp.curriculum.name%></span>

    <p><%= @camp.curriculum.description %></p>

    <h5>Camp Details</h5>
    
    <p><strong>Location: </strong><%= @camp.location.name %></p>
    <p><strong>Dates: </strong><%= @camp.start_date.strftime("%m/%d/%y") %> - <%= @camp.end_date.strftime("%m/%d/%y") %></p>
    <p><strong>Time of Day: </strong><%= @camp.time_slot == "am" ? "Morning" : "Afternoon" %></p>
    <p><strong>Chess Levels: </strong><%= @camp.curriculum.min_rating %> - <%= @camp.curriculum.max_rating %></p>
    <p><strong>Max Enrollment: </strong><%= @camp.max_students %></p>
    <p><strong>Active: </strong><%= @camp.active ? "Camp is currently active" : "camp is currently inactive." %></p>
    <p><strong>Camp: </strong>$<%= @camp.cost %>0</p>
    
    
    <% if CampInstructor.where(camp_id: @camp.id).length.zero? %>
      <p><strong>Camp Instructors: </strong> No instructors at this time</p>
    <% else %>
      <p><strong>Camp Instructors: </strong><%= CampInstructor.where(camp_id: @camp.id).map{ |ci| ci.instructor.proper_name } %></p>
    <% end %>  
    
    
  </div>
  <div class="card-action">
    <%= link_to 'Edit', edit_camp_path(@camp), :class=>"btn waves-effect waves-light blue" %>
    <%= link_to 'Back', camps_path, :class=>"btn waves-effect waves-light blue" %>
  </div>
</div>