config/routes.rb
Rails.application.routes.draw do
    
    resources :controllers
    resources :camps
    resources :camp_instructors
    resources :curriculums
    resources :instructors
    resources :locations
    resources :users
    resources :credit_cards
    resources :curriculums
    resources :families
    resources :students
    resources :registrations
    
    root to: 'home_page#index'
    
    resources :about_us
    resources :contact_us
    resources :privacy_page
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/family.rb
class Family < ApplicationRecord
    
    has_many :students
    has_many :registrations, through: :students
    belongs_to :user
    
    #validations
    
    validates_presence_of :family_name
    validates_presence_of :parent_first_name
    
    before_destroy :delete_error
    
    #scopes
    
    scope :alphabetical, -> { order('family_name, parent_first_name') }
    scope :active, -> { where(active: true) }
    scope :inactive, -> { where(active: false) }
    
    #functions
    
    
    def make_inactive
        self.active = false
        self.save
        family_made_inactive
    end
    
    private
    
    
    def delete_error
        throw(:abort)
    end
    
    def delete_registrations
        self.registrations.select{|r| r.camp.start_date > Date.current}.each{|d| d.destroy}
    end
    
    def family_made_inactive
        if self.active == false
            delete_registrations
            self.students.update_all(active: false) 
        end
    end
    
    
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:family_name, :parent_first_name, :user_id, :active)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_with(model: @family, local: true) do |form| %>
  <% if @family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% @family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :family_name %>
    <%= form.text_field :family_name, id: 'family_name' %>
  </div>

  <div class="field">
    <%= form.label :parent_first_name %>
    <%= form.text_field :parent_first_name, id: 'parent_first_name' %>
  </div>
  
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: 'user_id' %>
  </div>
  
  <div class="checkbox">
    <label><%= form.check_box :active %> Is this family active?</label>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<br><br><br>

<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<br><br><br>

<p id="notice"><%= notice %></p>

<% if @families.empty? %>
  <h3>There are no families in the system at this time</h3>
<% else %>

  <h2>Families</h2>

  <table>
    <thead>
      <tr>
        
        <th>Family Name</th>
        <th>Parent First Name</th>
        <th>User ID</th>
        <th colspan = "3"></th>
        
      </tr>
    </thead>
    
    <tbody>
      <% @families.each do |family| %>
      <tr>
        <td> <%= link_to family.family_name, family %></td>
        <td> <%= link_to family.parent_first_name, family %></td>
        <td> <%= link_to family.user_id, family %></td>
        
        <td> <%= link_to 'Edit', edit_family_path(family) %></td>
        
      </tr>
      <% end %>
    </tbody>
  </table>


  <% end %>

<br>
<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<br><br><br>

<h1>New Family</h1>

<%= render 'form', curriculum: @family %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<br><br><br>

<p id="notice"><%= notice %></p>

<h3> Family Details</h3>

<p>
  <strong>Family Name:</strong>
  <%= @family.family_name %>
</p>

<p>
  <strong>Parent First Name:</strong>
  <%= @family.parent_first_name %>
</p>

  <strong>Active:</strong>
  <%= @family.active ? "Yes" : "No" %>
</p>