config/routes.rb
Rails.application.routes.draw do
    
    resources :controllers
    resources :camps
    resources :camp_instructors
    resources :curriculums
    resources :instructors
    resources :locations
    resources :users
    resources :credit_cards
    resources :curriculums
    resources :families
    resources :students
    resources :registrations
    
    root to: 'home_page#index'
    
    resources :about_us
    resources :contact_us
    resources :privacy_page
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/instructor.rb
class Instructor < ApplicationRecord
  # relationships
  belongs_to :user
  has_many :camp_instructors
  has_many :camps, through: :camp_instructors

  # validations
  validates_presence_of :first_name
  validates_presence_of :last_name


  # scopes
  scope :alphabetical, -> { order('last_name, first_name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :needs_bio, -> { where('bio IS NULL') }

  # class methods
  def self.for_camp(camp)
    # the 'instructive way'... (which I told you if you asked me for help)
    CampInstructor.where(camp_id: camp.id).map{ |ci| ci.instructor }
    # the easy way... 
    # camp.instructors
  end

  # callbacks
  
  before_update :if_user_is_inactive_deactivate
  after_rollback :convert_to_inactive_and_remove_future_camps
  
  
  before_destroy do 
    check_if_this_instructor_taught_past_camps
    if errors.present?
      @destroyable = false
      throw(:abort)
    else
      self.user.destroy
      
    end
  end

  # instance methods
  def name
    last_name + ", " + first_name
  end
  
  def proper_name
    first_name + " " + last_name
  end

  private
  
  def if_user_is_inactive_deactivate
    if self.active == false
      self.user.active = false 
      self.user.save 
    end
  end 
  
  def check_if_this_instructor_taught_past_camps
    unless self.camps.past.empty?
      errors.add(:base, "Instructor has taught past camps")
    end 
  end
  
  def removing_future_camps
    self.camp_instructors.select{|ci| ci.camp.start_date >= Date.current}.each{|ci| ci.destroy}
  end 
  
  def delete_user
    self.user.destroy
  end 
  
  def convert_to_inactive_and_remove_future_camps
    if @destroyable == false
      removing_future_camps
      delete_user
      self.active = false 
    end 
  end


end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
       params.require(:instructor).permit(:user_id, :first_name, :last_name, :bio, :active)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
   <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, options_from_collection_for_select(User.all, 'id', 'username') %>
  </div>
  
  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: 'instructor_first_name' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: 'instructor_last_name' %>
  </div>
  
  <div class="field">
    <%= form.label :bio %>
    <%= form.text_field :bio, id: 'instructor_bio' %>
  </div>

  <div class="checkbox">
    <label><%= form.check_box :active %> Is this instructor active?</label>
  </div>
    


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<br><br><br>

<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<br><br><br>


<p id="notice"><%= notice %></p>

<% if @instructors.empty? %>
  <h4>There are no instructors in the system at this time</h4>
<% else %>

  <h2>Instructors</h2>
  
  <table>
    <thead>
      <tr>
        
        <th>Name</th>
        <th>Camps</th>
        <th>Active?</th>
        
      </tr>
    </thead>
    
    <tbody>
      <% @instructors.each do |instructor| %>
      <tr>
        <td> <%= link_to instructor.name, instructor %></td>
        <td> <%= instructor.camps.size %> </td>
        <td> <%= link_to instructor.active, instructor %></td>

        <td> <%= link_to 'Edit', edit_instructor_path(instructor) %></td>

        
      </tr>
      <% end %>
    </tbody>
  </table>
  


  <% end %>

<br>
<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<br><br><br>

<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<br><br><br>

<h3><%= @instructor.proper_name %></h3>

<h5>Basic Information</h5>

<p><strong>Name: </strong><%= @instructor.proper_name %></p>
<p><strong>Bio: </strong><%= @instructor.bio %></p>
<p><strong>Active:</strong>
  <%= @instructor.active ? "Yes" : "No" %>
</p>

<h5>Upcoming Camps</h5> 

<table>
    <thead>
      <tr>
  
        <th>Name</th>
        <th>Start</th>
        <th>End</th>
        <th>Time</th>
        <th>Max Students</th>
        
      </tr>
    </thead>
    
    <tbody>
      <% @instructor.camps.each do |camp| %>
      <tr>
        
        <td> <%= link_to camp.curriculum.name, camp %></td>
        <td> <%= link_to camp.start_date.strftime("%m/%d/%y"), camp %></td>
        <td> <%= link_to camp.end_date.strftime("%m/%d/%y"), camp %></td>
        <td> <%= link_to camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
        <td> <%= link_to camp.max_students, camp %></td>
        
        <td> <%= link_to 'Edit', edit_camp_path(camp) %></td>
        
      </tr>
      <% end %>
    </tbody>
    

  </table>